### ISSUE TITLE
Failure to Decode Unicode Escape Sequences when using Stanford CoreNLP

### ISSUE THREAD

**Issue by nuthanmunaiah** [andymeneely/sira-nlp#21]
# Description

When using the Stanford CoreNLP server for sentiment analysis (and sentence parsing), we get a bunch of `simplejson.scanner.JSONDecodeError: Invalid control character '\x1a' at: line 1 column 36688 (char 36687)` errors.

# Proposed Solution

As described in an answer to a Stack Overflow question (https://stackoverflow.com/a/4296045), JSON does not support `\xNN` escape sequence. So the solution would be to convert the `\xNN` sequences to `\uNNNN` sequence in the raw response from CoreNLP. Once the invalid escape sequences are replaced, `json.loads()` can be used to load the JSON object from response.

**Comment by meyersbs** [comment]
## Problem

There are a number of ways to convert `\xNN` to `\uNNNN`, however, none of them do quite what we expect in the current situation. The problem is that CoreNLP is building a string representation of a `JSON` objects, and sometimes that string contains escape codes like `\x1a`. Unfortunately, converting from `\x` to `\u` and then trying to load the `JSON` object still fails -- `JSON` simply doesn't play nicely with escape codes.

## Solution

I created a helper function `to_json` that takes in a string representation of a `JSON` object, removes all `\xNN` characters and returns a proper `JSON` object. See Commit [33f4b0b](https://github.com/andymeneely/sira-nlp/commit/33f4b0b96887bd949b864b0fc5b588855c1208bb) for implementation details.
